let direction="long";
const TERMS={hebel:{title:"Hebel",level:"Level 1 · Grundlagen",text:"Ein Hebel vergrößert deine Positionsgröße. Dadurch können Gewinne und Verluste stärker ausfallen.",example:"100 € Margin mit 10x Hebel ergeben eine Position von 1.000 €.",mistake:"Typischer Fehler: Einen hohen Hebel nutzen, ohne vorher Stop-Loss und Risiko zu planen."},margin:{title:"Margin",level:"Level 1 · Grundlagen",text:"Margin ist die Sicherheitsleistung, die du für eine gehebelte Position hinterlegst.",example:"Bei 10x Hebel brauchst du für eine 1.000 € Position ungefähr 100 € Margin.",mistake:"Typischer Fehler: Margin mit maximalem Verlust verwechseln."},liquidation:{title:"Liquidation",level:"Level 2 · Risiko verstehen",text:"Liquidation bedeutet, dass die Börse deine Position automatisch schließt, wenn deine Margin nicht mehr ausreicht.",example:"Bei hohem Hebel kann bereits eine kleine Kursbewegung gegen dich gefährlich werden.",mistake:"Typischer Fehler: Ohne Stop-Loss handeln und hoffen, dass der Markt zurückkommt."},stoploss:{title:"Stop-Loss",level:"Level 2 · Risiko verstehen",text:"Ein Stop-Loss ist eine Order, die deine Position automatisch schließt, wenn ein bestimmter Verlustpunkt erreicht wird.",example:"Einstieg 100.000, Stop 99.000 = 1 % Stop-Abstand.",mistake:"Typischer Fehler: Den Stop nachträglich weiter wegziehen."},risiko:{title:"Risiko pro Trade",level:"Level 2 · Risiko verstehen",text:"Das Risiko pro Trade beschreibt, wie viel Prozent deines Kontos du bei einem Trade maximal verlieren möchtest.",example:"300 € Konto und 2 % Risiko = 6 € maximaler Verlust.",mistake:"Typischer Fehler: Nach Verlusten das Risiko erhöhen."},support:{title:"Support",level:"Level 3 · Charts lesen",text:"Support ist ein Preisbereich, in dem Käufer in der Vergangenheit häufig aktiv wurden.",example:"Wenn BTC mehrfach bei 98.000 reagiert, kann dieser Bereich als Support betrachtet werden.",mistake:"Typischer Fehler: Support als Garantie verstehen."}};
const $=id=>document.getElementById(id);
setTimeout(()=>{$("splash").classList.add("hidden");$("mainApp").classList.remove("hidden");renderTerms();calculate()},1200);
function go(page){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));$(page).classList.add("active");const map={home:["Home","Trading beginnt beim Verstehen."],tools:["Tools","Plane deinen Trade bewusst."],academy:["Academy","Lerne Schritt für Schritt."],journal:["Journal","Reflektiere deine Trades."],more:["Mehr","Einstellungen und Pro."]};$("pageTitle").textContent=map[page][0];$("pageSubtitle").textContent=map[page][1];document.querySelectorAll(".nav")[{home:0,tools:1,academy:2,journal:3,more:4}[page]].classList.add("active")}
function setDirection(next){direction=next;$("longBtn").classList.toggle("active",next==="long");$("shortBtn").classList.toggle("active",next==="short");calculate()}
function euro(v){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v)}
function calculate(){const balance=Number($("balance").value),riskPct=Number($("risk").value),lev=Number($("leverage").value),entry=Number($("entry").value),stop=Number($("stop").value);if(!balance||!riskPct||!lev||!entry||!stop||entry===stop){$("status").textContent="Eingaben prüfen";return}if(direction==="long"&&stop>=entry){$("status").textContent="Stop unter Einstieg";return}if(direction==="short"&&stop<=entry){$("status").textContent="Stop über Einstieg";return}const riskEuro=balance*riskPct/100,dist=Math.abs(entry-stop)/entry,pos=riskEuro/dist,margin=pos/lev,tp2=direction==="long"?entry+entry*dist*2:entry-entry*dist*2;$("loss").textContent=euro(riskEuro);$("position").textContent=euro(pos);$("margin").textContent=euro(margin);$("tp2").textContent=tp2.toLocaleString("de-DE",{maximumFractionDigits:2});$("status").textContent=margin>balance?"Margin > Konto":riskPct>2?"Risiko hoch":"OK"}
["balance","risk","leverage","entry","stop"].forEach(id=>document.addEventListener("input",e=>{if(e.target&&e.target.id===id)calculate()}));
function renderTerms(){const q=($("search")?.value||"").toLowerCase(),list=$("termList");if(!list)return;list.innerHTML="";Object.entries(TERMS).filter(([k,t])=>t.title.toLowerCase().includes(q)||k.includes(q)).forEach(([k,t])=>{const b=document.createElement("button");b.innerHTML=`<b>${t.title}</b><br><span>${t.level}</span>`;b.onclick=()=>openTerm(k);list.appendChild(b)})}
function openTerm(key){const t=TERMS[key];if(!t)return;$("modalLevel").textContent=t.level;$("modalTitle").textContent=t.title;$("modalText").textContent=t.text;$("modalExample").textContent=t.example;$("modalMistake").textContent="⚠️ "+t.mistake;$("modal").classList.remove("hidden")}
function hideModal(){$("modal").classList.add("hidden")}
function closeModal(e){if(e.target.id==="modal")hideModal()}
if("serviceWorker"in navigator){addEventListener("load",()=>navigator.serviceWorker.register("sw.js"))}
